import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
// import { SessionProvider } from "next-auth/react";
import { AuthProvider } from "./provider";
import { League_Spartan } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spartan = League_Spartan({
  subsets: ['latin'],
  display: 'swap'
})

// const AuthProvider = ({ children }) => {
//   return <SessionProvider>{children}</SessionProvider>;
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <SessionProvider>
    
      <StoreProvider>
        <html lang="en">
          <AuthProvider>
            <body>{children}</body>
          </AuthProvider>
        </html>
      </StoreProvider>
    
    //  </SessionProvider> 
  );
}
